---
- name: Install packages
  hosts: vmware
  become: true
  tasks:
  - name: Install git
    yum:
      name: git
      state: present
      
  - name: Install tree
    yum:
      name: tree
      state: present

  - name: Create a directory
    file:
      path: /home/ansible/test-path
      state: directory
      owner: ec2-user

  - name: Create a file
    file:
      path: /home/ansible/test-file
      state: touch

  - name: Copy file to remote host
    copy:
      src: /opt/ansible/index.html
      dest: /home/ansible
      mode: 0600
      owner: ansadmin
      group: ansadmin
